version: "3.9"

networks:
  net1:

services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: challenge_telconet
      MYSQL_USER: challenge_admin
      MYSQL_PASSWORD: challenge12345
      MYSQL_ROOT_PASSWORD: root12345
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - net1

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports: 
      - "5000:5000"
    volumes:
      - ./src:/code
    depends_on:
      - mysql
    environment:
      FLASK_ENV: development
    networks: 
      - net1

  app:
    build: ./telco-app
    container_name: app
    depends_on:
      - backend
    ports:
      - "8000:80"
    networks:
      - net1